name: release dfx-qrcode

on:
  push:
    tags:
      - 'dfx-qrcode*'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v4
        with:
          install: true

      - name: test dfx-qrcode
        run: pnpm exec nx test dfx-qrcode --configuration=ci --coverageReporters=cobertura

      - name: setup coverage report
        uses: ./.github/actions/setup-coverage-report
        with:
          path: coverage/libs/dfx-qrcode/cobertura-coverage.xml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v4
        with:
          install: true

      - name: build dfx-qrcode
        run: pnpm exec nx build dfx-qrcode

      - name: zip dfx-qrcode
        run: |
          cd ./dist/libs/
          zip -r "dfx-qrcode.zip" ./dfx-qrcode
          cd -

      - uses: actions/upload-artifact@v4
        name: create dfx-qrcode artifact
        with:
          name: dfx-qrcode
          path: ./dist/libs/dfx-qrcode.zip
          retention-days: 1

  release-github:
    name: Release zip to github releases
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v5
        with:
          name: dfx-qrcode
          path: ./dist

      - name: get dfx-qrcode version
        id: get-version
        shell: bash
        run: echo "VERSION=$(node -p "require('./libs/dfx-qrcode/package.json').version")" >> $GITHUB_OUTPUT

      - name: set to versioned zip dfx-qrcode-v${{ steps.get-version.outputs.VERSION }}.zip
        shell: bash
        run: |
          mkdir releases
          cp "./dist/dfx-qrcode.zip" "./releases/dfx-qrcode-v${{ steps.get-version.outputs.VERSION }}.zip"

      - name: releases lookup
        run: |
          cd releases
          ls -la
          du -hs
          cd -

      - name: get only latest changelog
        run: |
          ./tools/scripts/extractLatestVersionChangelog.sh ./libs/dfx-qrcode/CHANGELOG.md
          cat RELEASE_CHANGELOG.md

      - name: create dfx-qrcode-v${{ steps.get-version.outputs.VERSION }} release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body_path: ./RELEASE_CHANGELOG.md
          files: ./releases/dfx-qrcode-v${{ steps.get-version.outputs.VERSION }}.zip

  release-npm:
    name: Release to npm registry
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '24'

      - uses: actions/download-artifact@v5
        with:
          name: dfx-qrcode
          path: ./dist

      - name: unzip
        shell: bash
        run: |
          cd dist
          unzip dfx-qrcode.zip
          cd -

      - name: dist lookup
        shell: bash
        run: |
          cd dist/dfx-qrcode
          ls -la
          du -hs
          cd -

      - name: publish to npm registry
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          cd dist/dfx-qrcode/
          npm publish
