name: release ng-icons-manager

on:
  push:
    tags:
      - 'ng-icons-manager*'

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for GitHub release action

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v5
        with:
          install: true

      - name: test ng-icons-manager
        run: pnpm exec nx test ng-icons-manager --configuration=ci --coverageReporters=cobertura

      - name: setup coverage report
        uses: ./.github/actions/setup-coverage-report
        with:
          path: coverage/libs/ng-icons-manager/cobertura-coverage.xml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v5
        with:
          install: true

      - name: build ng-icons-manager
        run: pnpm exec nx build ng-icons-manager

      - name: zip ng-icons-manager
        run: |
          cd ./dist/libs/
          zip -r "ng-icons-manager.zip" ./ng-icons-manager
          cd -

      - uses: actions/upload-artifact@v6
        name: create ng-icons-manager artifact
        with:
          name: ng-icons-manager
          path: ./dist/libs/ng-icons-manager.zip
          retention-days: 1

  release-github:
    name: Release zip to github releases
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v7
        with:
          name: ng-icons-manager
          path: ./dist

      - name: get ng-icons-manager version
        id: get-version
        shell: bash
        run: echo "VERSION=$(node -p "require('./libs/ng-icons-manager/package.json').version")" >> $GITHUB_OUTPUT

      - name: set to versioned zip ng-icons-manager-v${{ steps.get-version.outputs.VERSION }}.zip
        shell: bash
        run: |
          mkdir releases
          cp "./dist/ng-icons-manager.zip" "./releases/ng-icons-manager-v${{ steps.get-version.outputs.VERSION }}.zip"

      - name: releases lookup
        run: |
          cd releases
          ls -la
          du -hs
          cd -

      - name: get only latest changelog
        run: |
          ./tools/scripts/extractLatestVersionChangelog.sh ./libs/ng-icons-manager/CHANGELOG.md
          cat RELEASE_CHANGELOG.md

      - name: create ng-icons-manager-v${{ steps.get-version.outputs.VERSION }} release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body_path: ./RELEASE_CHANGELOG.md
          files: ./releases/ng-icons-manager-v${{ steps.get-version.outputs.VERSION }}.zip

  release-npm:
    name: Release to npm registry
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '24'

      - uses: actions/download-artifact@v7
        with:
          name: ng-icons-manager
          path: ./dist

      - name: unzip
        shell: bash
        run: |
          cd dist
          unzip ng-icons-manager.zip
          cd -

      - name: dist lookup
        shell: bash
        run: |
          cd dist/ng-icons-manager
          ls -la
          du -hs
          cd -

      - name: publish to npm registry
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          cd dist/ng-icons-manager/
          npm publish
