name: release dfts-qrcode

on:
  push:
    tags:
      - 'dfts-qrcode*'

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v4
        with:
          install: true

      - name: test dfts-qrcode
        run: pnpm exec nx test dfts-qrcode --configuration=ci --coverageReporters=cobertura

      - name: setup coverage report
        uses: ./.github/actions/setup-coverage-report
        with:
          path: coverage/libs/dfts-qrcode/cobertura-coverage.xml

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v4
        with:
          install: true

      - name: build dfts-qrcode
        run: pnpm exec nx build dfts-qrcode

      - name: zip dfts-qrcode
        run: |
          cd ./dist/libs/
          zip -r "dfts-qrcode.zip" ./dfts-qrcode
          cd -

      - uses: actions/upload-artifact@v4
        name: create dfts-qrcode artifact
        with:
          name: dfts-qrcode
          path: ./dist/libs/dfts-qrcode.zip
          retention-days: 1

  release-github:
    name: Release zip to github releases
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v5
        with:
          name: dfts-qrcode
          path: ./dist

      - name: get dfts-qrcode version
        id: get-version
        shell: bash
        run: echo "VERSION=$(node -p "require('./libs/dfts-qrcode/package.json').version")" >> $GITHUB_OUTPUT

      - name: set to versioned zip dfts-qrcode-v${{ steps.get-version.outputs.VERSION }}.zip
        shell: bash
        run: |
          mkdir releases
          cp "./dist/dfts-qrcode.zip" "./releases/dfts-qrcode-v${{ steps.get-version.outputs.VERSION }}.zip"

      - name: releases lookup
        run: |
          cd releases
          ls -la
          du -hs
          cd -

      - name: get only latest changelog
        run: |
          ./tools/scripts/extractLatestVersionChangelog.sh ./libs/dfts-qrcode/CHANGELOG.md
          cat RELEASE_CHANGELOG.md

      - name: create dfts-qrcode-v${{ steps.get-version.outputs.VERSION }} release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body_path: ./RELEASE_CHANGELOG.md
          files: ./releases/dfts-qrcode-v${{ steps.get-version.outputs.VERSION }}.zip

  release-npm:
    name: Release to npm registry
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/download-artifact@v5
        with:
          name: dfts-qrcode
          path: ./dist

      - name: unzip
        shell: bash
        run: |
          cd dist
          unzip dfts-qrcode.zip
          cd -

      - name: dist lookup
        shell: bash
        run: |
          cd dist/dfts-qrcode
          ls -la
          du -hs
          cd -

      - name: publish to npm registry
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          cd dist/dfts-qrcode/
          npm publish
